workflows:
  sa3r-android-apk:
    name: Sa3r Android APK
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
    scripts:
      - name: Generate Android platform
        script: |
          cd mobile
          flutter create --platforms=android .

      - name: Get Flutter packages
        script: |
          cd mobile
          flutter pub get

      - - name: Build APK
  script: |
    cd mobile
    flutter build apk --debug --dart-define=SA3R_API_URL=https://bpphsjvbvfalsclyuecm.supabase.co/functions/v1/sa3r-api
    ls -lh build/app/outputs/flutter-apk/
    artifacts:
  - $CM_BUILD_DIR/mobile/build/app/outputs/flutter-apk/*.apk
